/*
 * this file should be compiled as pure C,
 * and should be added to project manually
 */

#define luaall_c

#include "../../../zf3rd/_tmp/lua/lapi.c"
#undef ldebug_h
#undef getline
#include "../../../zf3rd/_tmp/lua/lcode.c"
#undef ldebug_h
#undef getline
#include "../../../zf3rd/_tmp/lua/ldebug.c"
#undef ldebug_h
#undef getline
#include "../../../zf3rd/_tmp/lua/ldo.c"
#undef ldebug_h
#undef getline
#include "../../../zf3rd/_tmp/lua/ldump.c"
#undef ldebug_h
#undef getline
#include "../../../zf3rd/_tmp/lua/lfunc.c"
#undef ldebug_h
#undef getline
#include "../../../zf3rd/_tmp/lua/lgc.c"
#undef ldebug_h
#undef getline
#include "../../../zf3rd/_tmp/lua/llex.c"
#undef ldebug_h
#undef getline
#include "../../../zf3rd/_tmp/lua/lmem.c"
#undef ldebug_h
#undef getline
#include "../../../zf3rd/_tmp/lua/lobject.c"
#undef ldebug_h
#undef getline
#include "../../../zf3rd/_tmp/lua/lopcodes.c"
#undef ldebug_h
#undef getline
#include "../../../zf3rd/_tmp/lua/lparser.c"
#undef ldebug_h
#undef getline
#include "../../../zf3rd/_tmp/lua/lstate.c"
#undef ldebug_h
#undef getline
#include "../../../zf3rd/_tmp/lua/lstring.c"
#undef ldebug_h
#undef getline
#include "../../../zf3rd/_tmp/lua/ltable.c"
#undef ldebug_h
#undef getline
#include "../../../zf3rd/_tmp/lua/ltm.c"
#undef ldebug_h
#undef getline
#include "../../../zf3rd/_tmp/lua/lundump.c"
#undef ldebug_h
#undef getline
#include "../../../zf3rd/_tmp/lua/lvm.c"
#undef ldebug_h
#undef getline
#include "../../../zf3rd/_tmp/lua/lzio.c"
#undef ldebug_h
#undef getline

#include "../../../zf3rd/_tmp/lua/lauxlib.c"
#undef ldebug_h
#undef getline
#include "../../../zf3rd/_tmp/lua/lbaselib.c"
#undef ldebug_h
#undef getline
#include "../../../zf3rd/_tmp/lua/ldblib.c"
#undef ldebug_h
#undef getline
#include "../../../zf3rd/_tmp/lua/liolib.c"
#undef ldebug_h
#undef getline
#include "../../../zf3rd/_tmp/lua/linit.c"
#undef ldebug_h
#undef getline
#include "../../../zf3rd/_tmp/lua/lmathlib.c"
#undef ldebug_h
#undef getline
#include "../../../zf3rd/_tmp/lua/loadlib.c"
#undef ldebug_h
#undef getline
#include "../../../zf3rd/_tmp/lua/loslib.c"
#undef ldebug_h
#undef getline
#include "../../../zf3rd/_tmp/lua/lstrlib.c"
#undef ldebug_h
#undef getline
#include "../../../zf3rd/_tmp/lua/ltablib.c"
#undef ldebug_h
#undef getline

